[package]
name = "audio2x"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["face", "emotion"]
face = ["dep:audio2face"]
emotion = ["dep:audio2emotion"]
cuda = ["audio2x-cuda/cuda", "audio2x-inference/cuda", "audio2face?/cuda", "audio2emotion?/cuda"]
tensorrt = ["cuda", "audio2x-inference/tensorrt", "audio2face?/tensorrt", "audio2emotion?/tensorrt"]

[dependencies]
audio2x-core.workspace = true
audio2x-cuda.workspace = true
audio2x-inference.workspace = true
audio2face = { workspace = true, optional = true }
audio2emotion = { workspace = true, optional = true }
serde_json.workspace = true

[[bin]]
name = "audio2x-regression"
path = "src/bin/audio2x-regression.rs"
required-features = ["face", "emotion", "tensorrt"]

[[bin]]
name = "audio2x-diffusion"
path = "src/bin/audio2x-diffusion.rs"
required-features = ["face", "emotion", "tensorrt"]

[[bin]]
name = "audio2x-emotion"
path = "src/bin/audio2x-emotion.rs"
required-features = ["face", "emotion", "tensorrt"]

[[bin]]
name = "audio2x-model"
path = "src/bin/audio2x-model.rs"

[[bin]]
name = "audio2x-benchmark"
path = "src/bin/audio2x-benchmark.rs"
required-features = ["face", "emotion", "tensorrt"]

[lints]
workspace = true
